const asserts = require ('./topics/about_asserts.js');
const operators = require ('./topics/about_operators.js');
const equality = require ('./topics/about_equality.js');
const truthyness = require ('./topics/about_truthyness.js');
const assignment = require ('./topics/about_assignment.js');
const control_structures = require ('./topics/about_control_structures.js');
const strings = require ('./topics/about_strings.js');
const numbers = require ('./topics/about_numbers.js');
const objects = require ('./topics/about_objects.js');
const arrays = require ('./topics/about_arrays.js');
const reflection = require ('./topics/about_reflection.js');
const prototype_chain = require ('./topics/about_prototype_chain.js');
const prototypal_inheritance = require ('./topics/about_prototypal_inheritance.js');
const functions_and_closure = require ('./topics/about_functions_and_closure.js');
const about_this = require ('./topics/about_this.js');
const scope = require ('./topics/about_scope.js');
const regular_expressions = require ('./topics/about_regular_expressions.js');

asserts.test();
operators.test();
equality.test();
truthyness.test();
assignment.test();
control_structures.test();
strings.test();
numbers.test();
objects.test();
arrays.test();
reflection.test();
prototype_chain.test();
prototypal_inheritance.test();
functions_and_closure.test();
about_this.test();
scope.test();
regular_expressions.test();
